version: "3.7"

services:
  caddy:
    image: caddy:latest
    #restart: unless-stopped
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - 'C:\Users\Niki\Documents\GitHub\cfsync_web\Caddyfile:/etc/caddy/Caddyfile'
      - 'C:\armaserver\mods:/var/www/modsrepo/'
      - 'C:\Users\Niki\Documents\GitHub\cfsync_web\squad\:/var/www/squad/'
      - 'C:\armaserver\arma\cfsync:/var/www/cfsync/'
    restart: unless-stopped